name: uix_example_tests
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.9.1'
dependencies:
  browser: any
  uix:
    git: 'https://github.com/localvoid/uix'
dev_dependencies:
  unittest: any
